apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dbstc6jtu-nodejs
  janus-idp.io/tekton: dbstc6jtu-nodejs
  backstage.io/kubernetes-id: dbstc6jtu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dbstc6jtu-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
