apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dbstc6jtu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dbstc6jtu-nodejs 
  name: dbstc6jtu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dbstc6jtu-nodejs 
